apiVersion: v1
kind: Secret
metadata:
  name: pfx-password
  namespace: default
type: Opaque
data:
  password: <BASE64_ENCODED_PASSWORD>
---
apiVersion: v1
kind: Secret
metadata:
  name: pfx-certificate-from-secret
  namespace: default
  annotations:
    # Enable PFX to PEM conversion
    pfx-tls.kubernetes.io/convert: "true"
    # Optional: Specify the key containing PFX data (default: "pfx")
    pfx-tls.kubernetes.io/pfx-key: "pfx"
    # Reference to secret containing password
    pfx-tls.kubernetes.io/password-secret-name: "pfx-password"
    pfx-tls.kubernetes.io/password-secret-key: "password"
type: Opaque
data:
  # Base64 encoded PFX certificate
  pfx: <BASE64_ENCODED_PFX_DATA>
