apiVersion: v1
kind: Secret
metadata:
  name: pfx-certificate
  namespace: default
  annotations:
    # Enable PFX to PEM conversion
    pfx-tls.kubernetes.io/convert: "true"
    # Optional: Specify the key containing PFX data (default: "pfx")
    pfx-tls.kubernetes.io/pfx-key: "pfx"
    # Optional: Provide password directly (not recommended for production)
    pfx-tls.kubernetes.io/password: ""
type: Opaque
data:
  # Base64 encoded PFX certificate
  pfx: <BASE64_ENCODED_PFX_DATA>
